"""chunks y corpus_versions con pgvector

Revision ID: 8b763bb572e8
Revises: 
Create Date: 2026-09-01 20:30:43.799015

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b763bb572e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The extension has to exist before a column can be typed VECTOR.
    # Autogenerate does not know that, so it goes in by hand.
    # || La extension tiene que existir antes de que una columna pueda ser de
    # tipo VECTOR. Autogenerate no lo sabe, asi que va a mano.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('doc_version', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', text)", persisted=True), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('bullet_path', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=True),
    sa.Column('document_kind', sa.String(length=32), nullable=True),
    sa.Column('module_code', sa.String(length=32), nullable=True),
    sa.Column('module_name', sa.Text(), nullable=True),
    sa.Column('submodule_code', sa.String(length=32), nullable=True),
    sa.Column('submodule_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'doc_version', 'content_hash', name='uq_chunks_tenant_version_hash')
    )
    op.create_index('ix_chunks_content_tsv', 'chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_chunks_module_code', 'chunks', ['module_code'], unique=False)
    op.create_index('ix_chunks_tenant_version', 'chunks', ['tenant_id', 'doc_version'], unique=False)
    op.create_table('corpus_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('doc_version', sa.String(length=128), nullable=False),
    sa.Column('corpus_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='loaded', nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'doc_version', name='uq_corpus_versions_tenant_version')
    )
    op.create_index('uq_corpus_versions_one_active_per_tenant', 'corpus_versions', ['tenant_id'], unique=True, postgresql_where="status = 'active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_corpus_versions_one_active_per_tenant', table_name='corpus_versions', postgresql_where="status = 'active'")
    op.drop_table('corpus_versions')
    op.drop_index('ix_chunks_tenant_version', table_name='chunks')
    op.drop_index('ix_chunks_module_code', table_name='chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_index('ix_chunks_content_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_table('chunks')
    # The extension is deliberately NOT dropped: something else may have
    # created it, and DROP EXTENSION would take every other table that uses it
    # with it.
    # || La extension NO se borra a proposito: puede haberla creado otra cosa,
    # y un DROP EXTENSION se llevaria por delante toda otra tabla que la use.
    # ### end Alembic commands ###
