"""window_type_name en chunks

Revision ID: d2c3d1071dbd
Revises: d279df786b34
Create Date: 2026-09-02 17:35:12.573819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c3d1071dbd'
down_revision: Union[str, Sequence[str], None] = 'd279df786b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('window_type_name', sa.String(length=48), nullable=True))
    op.create_index('ix_chunks_window_type', 'chunks', ['tenant_id', 'doc_version', 'window_type_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_window_type', table_name='chunks')
    op.drop_column('chunks', 'window_type_name')
    # ### end Alembic commands ###
