"""un solo job de ingesta corriendo, garantizado por la base

Revision ID: 3d59e9c3abb5
Revises: a01853163726
Create Date: 2026-09-02 22:20:00.529916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d59e9c3abb5'
down_revision: Union[str, Sequence[str], None] = 'a01853163726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.create_index('uq_ingestion_jobs_one_running', 'ingestion_jobs', ['status'], unique=True, postgresql_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ingestion_jobs_one_running', table_name='ingestion_jobs', postgresql_where=sa.text("status = 'running'"))
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    # ### end Alembic commands ###
