"""chunks.source_type: keep the door open for other source types

Revision ID: 62457660a177
Revises: d2c3d1071dbd
Create Date: 2026-09-02 21:36:17.998267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62457660a177'
down_revision: Union[str, Sequence[str], None] = 'd2c3d1071dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('source_type', sa.String(length=32), server_default='functional_spec', nullable=False))
    op.drop_constraint(op.f('uq_chunks_tenant_version_hash'), 'chunks', type_='unique')
    op.create_unique_constraint('uq_chunks_tenant_version_hash', 'chunks', ['tenant_id', 'doc_version', 'source_type', 'content_hash'])
    op.create_index('ix_chunks_source_type', 'chunks', ['tenant_id', 'doc_version', 'source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_source_type', table_name='chunks')
    op.drop_constraint('uq_chunks_tenant_version_hash', 'chunks', type_='unique')
    op.create_unique_constraint(op.f('uq_chunks_tenant_version_hash'), 'chunks', ['tenant_id', 'doc_version', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunks', 'source_type')
    # ### end Alembic commands ###
