"""agent_profiles: proveedor junto al modelo

Revision ID: c0afa4f128bd
Revises: b15380641ff9
Create Date: 2026-09-04 10:23:02.961457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0afa4f128bd'
down_revision: Union[str, Sequence[str], None] = 'b15380641ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profiles', sa.Column('provider', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_profiles', 'provider')
    # ### end Alembic commands ###
