"""process_map_edges

Revision ID: d279df786b34
Revises: 8b763bb572e8
Create Date: 2026-09-02 11:11:55.941073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd279df786b34'
down_revision: Union[str, Sequence[str], None] = '8b763bb572e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_map_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('doc_version', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('edge_type', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'doc_version', 'source', 'target', 'edge_type', name='uq_process_map_edges_identity')
    )
    op.create_index('ix_process_map_edges_source', 'process_map_edges', ['tenant_id', 'doc_version', 'source', 'edge_type'], unique=False)
    op.create_index('ix_process_map_edges_target', 'process_map_edges', ['tenant_id', 'doc_version', 'target', 'edge_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_process_map_edges_target', table_name='process_map_edges')
    op.drop_index('ix_process_map_edges_source', table_name='process_map_edges')
    op.drop_table('process_map_edges')
    # ### end Alembic commands ###
